Repository hellohaptik/relements, pull requests merged in 2019-09, with the labels that each got.

#36 ci(pipeline): release cycle fixes
  .releaserc
  .releaserc.js
  .travis.yml
  package.json
Labels: ci

#37 ci(releaserc): limited release on develop
  .releaserc.js
Labels: ci

#48 Release
  .releaserc.js
  .travis.yml
  README.md
  package.json
Labels: release

#47 ci(travis): netlify previews
  .releaserc.js
  .travis.yml
  README.md
  config/rollup.config.js
  package.json
  yarn.lock
Labels: ci

#17 tests(File): Tests for File Input Component #PE-569
  src/components/Inputs/File/File.js
  src/components/Inputs/File/File.mdx
  src/components/Inputs/File/File.storybook.js
  src/components/Inputs/File/__tests__/File.test.js
  src/components/Inputs/File/components/FilePlaceholder.js
  src/components/Inputs/File/components/ImagePlaceholder.js
  src/components/Inputs/File/components/ImageProgressBar.js
Labels: docs, enhancement, tests

#33 refactor(Odometer): Docs, test and examples #PE-566
  src/components/UI/Odometer/Odometer.js
  src/components/UI/Odometer/Odometer.mdx
  src/components/UI/Odometer/Odometer.storybook.js
  src/components/UI/Odometer/__tests__/Odometer.test.js
  src/components/UI/Odometer/components/Digit.js
Labels: docs, tests

#57 feat(Chips): added tests and docs for chips
  src/components/Context/Context.js
  src/components/Context/Provider.js
  src/components/Context/index.js
  src/components/Inputs/Checkbox/Checkbox.js
  src/components/Inputs/Checkbox/components/CheckboxOption.js
  src/components/Inputs/Checkbox/hooks/useCheckbox.js
  src/components/Inputs/Chips/Chips.js
  src/components/Inputs/Chips/Chips.mdx
  src/components/Inputs/Chips/Chips.storybook.js
  src/components/Inputs/Chips/__tests__/Chips.test.js
  src/components/Inputs/Date/components/Comparison/Comparison.js
  src/components/Inputs/Date/components/Input/Input.js
  src/components/Inputs/Date/components/Inputs/Inputs.js
  src/components/Inputs/Date/components/RangeComparison/RangePicker.js
  src/components/Inputs/Date/components/SinglePicker/SinglePicker.js
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/components/DropdownOption.js
  src/components/Inputs/Dropdown/components/DropdownOptions.js
  src/components/Inputs/Dropdown/hooks/useDropdown.js
  src/components/Inputs/Dropdown/hooks/useSearch.js
  src/components/Inputs/Radio/Radio.js
  src/components/Inputs/Radio/components/RadioOption.js
  src/components/Inputs/Radio/hooks/useRadio.js
  src/components/Inputs/RangeSlider/RangeSlider.js
  src/components/Inputs/RangeSlider/hooks/useRangeSlider.js
  src/components/Inputs/Tab/Tab.js
  src/components/Inputs/Tab/components/TabOption.js
  src/components/Inputs/Text/Text.js
  src/components/Inputs/Time/components/TimePicker/TimePicker.js
  src/components/Inputs/Time/components/TimePicker/index.js
  src/components/Inputs/Time/components/TimePickerInput/index.js
  src/components/Inputs/_common/ChipsInput.js
  src/components/Inputs/_common/Label.js
  src/components/Inputs/_common/TextInput.js
  src/components/Inputs/_common/hooks/useChips.js
  src/components/Inputs/_common/hooks/useInput.js
  src/components/Inputs/_common/hooks/useTabs.js
  src/components/Overlays/ContextMenu/components/ContextMenuItem.js
  src/components/Overlays/ContextMenu/components/ContextMenuPortal.js
  src/components/Overlays/Drawer/Drawer.js
  src/components/Overlays/Modal/Modal.js
  src/components/Overlays/Modal/components/ModalHeader.js
  src/components/Overlays/Tooltip/Tooltip.js
  src/components/Overlays/WithTooltip/WithTooltip.js
  src/components/UI/Accordion/components/AccordionItem.js
  src/components/UI/Button/Button.js
  src/components/UI/Calendar/Calendar.js
  src/components/UI/Icon/Icon.js
  src/components/UI/Icon/utils/getIcon.js
  src/components/UI/Loader/Loader.js
  src/components/UI/Pagination/Pagination.js
  src/components/UI/Tabs/Tabs.js
Labels: enhancement

#58 docs(chips): added Examples
  src/components/Inputs/Chips/Chips.mdx
Labels: docs
