Repository hellohaptik/relements, pull requests merged in 2019-10, with the labels that each got.

#97 fix(dropdown): fixes Focus/Blur
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/__tests__/Dropdown.test.js
  src/components/Inputs/_common/hooks/useInput.js
Labels: bug

#100 fix(file component): Incorrect arguments were passed to function
  src/api/_utils.js
  src/components/Inputs/File/File.js
  src/components/Inputs/File/File.mdx
  src/components/Inputs/File/__tests__/File.test.js
  src/components/Inputs/File/components/FilePlaceholder.js
  src/components/Inputs/File/components/ImagePlaceholder.js
Labels: bug

#105 fix(file component): Fixed onUploadsComplete function
  src/components/Inputs/File/File.js
  src/components/Inputs/File/File.scss
  src/components/UI/Loader/Loader.scss
Labels: bug

#108 fix(loader): fixed Loader
  src/components/UI/Loader/Loader.js
  src/components/UI/Loader/Loader.scss
Labels: bug

#119 fix(rangeslider): adds OnBlur Listener to set values
  src/components/Inputs/RangeSlider/RangeSlider.mdx
  src/components/Inputs/RangeSlider/__tests__/RangeSlider.test.js
  src/components/Inputs/RangeSlider/hooks/useRangeSlider.js
Labels: enhancement, hacktoberfest

#118 fix(text): added support for onKeyDown Prop
  src/components/Inputs/Text/Text.js
Labels: bug, hacktoberfest

#124 fix(chips): don't show cross button when chips disabled
  src/components/Inputs/Chips/Chips.mdx
  src/components/Inputs/_common/ChipsInput.js
Labels: bug, hacktoberfest

#126 fix(search): fixes Event Listener for Search
  src/components/Inputs/Search/Search.js
  src/hooks/useEnterKey/useEnterKey.js
Labels: bug, hacktoberfest

#125 fix(chipsinput): fixes Unexpeceted Ref Error
  src/components/Inputs/_common/ChipsInput.js
Labels: bug, hacktoberfest

#127 fix(chips): autofocus input field on focus of chips
  src/components/Inputs/_common/ChipsInput.js
Labels: bug, hacktoberfest
