Repository hellohaptik/relements, pull requests merged in 2020-06, with the labels that each got.

#310 fix(File): FileExtenstionRefactorWithValidation #BB-2016
  package.json
  src/components/Inputs/File/File.js
  src/components/Inputs/File/__tests__/File.test.js
Labels: bug

#308 enhancement(drawer): add width transition animation on width change
  src/components/Overlays/Drawer/Drawer.js
  src/components/Overlays/Drawer/Drawer.scss
  src/components/UI/Icon/utils/getIcon.js
  src/icons/expand.svg
  src/icons/shrink.svg
Labels: enhancement

#314 fix(readme): change can styled to can be styled
  README.md
Labels: bug

#315 fix(file): change image type jpg to jpeg for type comparison
  src/components/Inputs/File/File.js
  src/components/Inputs/File/__tests__/File.test.js
Labels: bug

#317 enhancement(file): Update alert box UI on validation #BB-2024
  src/components/Inputs/File/File.js
  src/components/Inputs/File/__tests__/File.test.js
Labels: enhancement

#319 fix(file): fix test cases for image/jpeg types
  src/components/Inputs/File/__tests__/File.test.js
Labels: bug

#321 fix(button): add transition effect for button on click
  src/components/UI/Button/Button.scss
Labels: bug

#324 feat(alert-bar): add new alert bar component
  src/components/UI/AlertBar/AlertBar.js
  src/components/UI/AlertBar/AlertBar.mdx
  src/components/UI/AlertBar/AlertBar.scss
  src/components/UI/AlertBar/AlertBar.storybook.js
  src/components/UI/AlertBar/__tests__/AlertBar.test.js
  src/components/UI/AlertBar/icons/defaultIcon.svg
  src/components/UI/AlertBar/index.js
  src/components/UI/AlertBar/utils.js
  src/components/UI/AlertBar/variables.scss
Labels: feature
