Repository hellohaptik/relements, pull requests merged in 2020-07, with the labels that each got.

#326 improvement(file): add onUpload prop to override default file upload
  config/exports.js
  src/components/Inputs/File/File.js
  src/components/Inputs/File/File.mdx
  src/components/Inputs/File/File.scss
  src/components/Inputs/File/__tests__/File.test.js
Labels: enhancement

#332 enhancement(alert-bar): Updated AlertBar component
  src/components/UI/AlertBar/AlertBar.js
  src/components/UI/AlertBar/AlertBar.scss
  src/components/UI/AlertBar/constants/index.js
  src/components/UI/AlertBar/utils.js
  src/components/UI/AlertBar/variables.scss
  src/components/UI/Icon/utils/getIcon.js
  src/components/index.js
  src/icons/infoV2.svg
Labels: enhancement

#335 enhancement(modal-header): added option for custom close icon in modal header
  src/components/Overlays/Modal/components/ModalHeader.js
Labels: enhancement

#336 feat(expandable-input-bar): new component for relements
  config/exports.js
  package.json
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.js
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.mdx
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.scss
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.storybook.js
  src/components/Inputs/ExpandableInputBar/__tests__/ExpandableInputBar.test.js
  src/components/Inputs/ExpandableInputBar/constants/index.js
  src/components/Inputs/ExpandableInputBar/index.js
  src/components/Inputs/ExpandableInputBar/variables.scss
  src/components/Inputs/Text/Text.js
  src/components/Inputs/_common/TextInput.js
  src/components/Inputs/index.js
  yarn.lock
Labels: feature

#340 fix(expandable-input-bar): fix onClick event
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.js
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.mdx
  src/components/Inputs/ExpandableInputBar/__tests__/ExpandableInputBar.test.js
Labels: bug

#341 feat(file): accepts customIcon to show on the placeholder
  src/components/Inputs/File/File.js
  src/components/Inputs/File/File.mdx
  src/components/Inputs/File/__tests__/File.test.js
  src/components/Inputs/File/components/FilePlaceholder.js
  src/components/Inputs/File/components/ImagePlaceholder.js
Labels: feature

#344 fix(dropdown): added prefix classname & tooltip for icon
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/components/Input/Input.js
Labels: bug

#346 fix(expendableinputbar): updated styles
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.js
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.mdx
  src/components/Inputs/ExpandableInputBar/ExpandableInputBar.scss
  src/helpers/DocBlocks/CodeBlock/CodeBlock.js
  src/icons/close-v2.svg
Labels: bug
