Repository hellohaptik/relements, pull requests merged in 2020-11, with the labels that each got.

#390 feat(dropdown): added checkbox view to dropdown
  .eslintrc
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/Dropdown.mdx
  src/components/Inputs/Dropdown/__tests__/Dropdown.test.js
  src/components/Inputs/Dropdown/components/Input/Input.js
  src/components/Inputs/Dropdown/components/Options/Options.js
  src/components/Inputs/Dropdown/components/Options/Options.scss
  src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.js
  src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.scss
  src/components/Inputs/Dropdown/components/WithCheckboxInput/index.js
  src/components/Inputs/Dropdown/utils/getOptions.js
Labels: feature

#393 fix(text): fixed text overflow
  src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.scss
Labels: bug

#394 feat(button): added secondary icon
  src/components/UI/Button/Button.js
  src/components/UI/Button/Button.mdx
  src/components/UI/Button/Button.scss
  src/components/UI/Button/__tests__/Button.test.js
Labels: enhancement
