Repository hellohaptik/relements, pull requests merged in 2021-06, with the labels that each got.

#502 enhancement(dropdown): variant with an icon
  src/Theme/dropdown.js
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/Dropdown.mdx
  src/components/Inputs/Dropdown/ThemedDropdown.js
  src/components/Inputs/Dropdown/components/Input/Input.js
  src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.js
  src/components/Inputs/_common/ThemedChipsInput.js
  src/components/Inputs/_common/ThemedTextInput.js
Labels: enhancement

#504 fix(tooltip): alignment fix of tooltip
  src/hooks/usePositioner/usePositioner.js
Labels: bug

#505 fix(input): size variant for input/dropdown
  src/Theme/dropdown.js
  src/Theme/textInput.js
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/Dropdown.mdx
  src/components/Inputs/Dropdown/ThemedDropdown.js
  src/components/Inputs/Dropdown/components/Input/Input.js
  src/components/Inputs/Dropdown/components/Option/Option.js
  src/components/Inputs/Dropdown/components/Options/Options.js
  src/components/Inputs/Text/Text.js
  src/components/Inputs/Text/Text.mdx
  src/components/Inputs/_common/TextInput.js
  src/components/Inputs/_common/ThemedTextInput.js
Labels: bug, enhancement

#510 fix(table): add tooltip support to themed table
  src/components/UI/Icon/Icon.js
  src/components/UI/Table/Table.js
  src/components/UI/Table/Table.storybook.js
  src/components/UI/Table/components/Body.Virtual.js
  src/components/UI/Table/components/Header.js
  src/components/UI/Table/components/Row.js
Labels: bug

#511 build(eslintrc): add and enable react hooks plugin
  .eslintrc
  package.json
  yarn.lock
Labels: dependencies, miscellaneous

#512 build(travis): update node version
  .travis.yml
Labels: ci

#513 fix(icon): add infoV3 icon Table Header
  src/components/UI/Icon/Icon.js
  src/components/UI/Icon/utils/getIcon.js
  src/components/UI/Table/components/Header.js
  src/icons/infoV3.svg
Labels: bug
