Repository hellohaptik/relements, pull requests merged in 2021-05, with the labels that each got.

#490 fix(build): update styled-components to remove react-is dependency
  config/rollup.config.js
  package.json
  yarn.lock
Labels: bug

#486 feat(tabs): migrate to new design systems
  src/components/UI/Tabs/Tabs.js
  src/components/UI/Tabs/Tabs.mdx
  src/components/UI/Tabs/ThemedTabs.js
  src/components/UI/Tabs/components/TabsItem.js
  src/components/UI/Tabs/components/ThemedTabsItem.js
Labels: feature

#494 feat(radio): add design component for Radio
  .gitignore
  src/Theme/components.js
  src/components/Inputs/Radio/Radio.js
  src/components/Inputs/Radio/Radio.storybook.js
  src/components/Inputs/Radio/components/Themed/Radio.js
  src/components/Inputs/Radio/components/Themed/RadioItem.js
Labels: enhancement
