Repository hellohaptik/relements, pull requests merged in 2021-03, with the labels that each got.

#436 feat(button): add design system variants
  src/Theme/Theme.js
  src/Theme/button.js
  src/Theme/shadows.js
  src/Theme/space.js
  src/components/UI/Button/Button.mdx
  src/components/UI/Button/ThemeButton.js
  src/components/UI/Button/__tests__/Button.test.js
  src/helpers/DocBlocks/CodeBlock/CodeBlock.js
Labels: enhancement

#439 miscellaneous(package): remove dev command
  package.json
Labels: miscellaneous

#433 miscellaneous(pr-template): add PR template, release drafter and mergeable
  .github/mergeable.yml
  .github/pull_request_template.md
  .github/release-drafter.yml
Labels: miscellaneous

#440 improvement(rangePicker): add max/min date support to range-picker
  src/components/Inputs/Date/Date.mdx
  src/components/Inputs/Date/__tests__/Date.basic.test.js
  src/components/Inputs/Date/components/RangeComparison/RangePicker.js
Labels: enhancement

#444 fix(date-picker): disable dates before start date, set max selectable compare dates
  src/components/Inputs/Date/Date.mdx
  src/components/Inputs/Date/components/RangeComparison/RangePicker.js
  src/components/UI/Calendar/Calendar.js
Labels: enhancement

#445 fix(calendar): default props, comparison date format to dayjs
  src/components/Inputs/Date/components/RangeComparison/RangePicker.js
  src/components/UI/Calendar/Calendar.js
Labels: enhancement

#454 fix(table): add row highlight
  src/components/UI/Table/Table.js
  src/components/UI/Table/Table.mdx
  src/components/UI/Table/components/Body.Virtual.js
  src/components/UI/Table/components/Body.js
  src/components/UI/Table/components/Row.js
Labels: enhancement

#456 fix(table): add active index row prop
  src/components/UI/Table/Table.js
  src/components/UI/Table/Table.mdx
Labels: bug

#450 feat(tooltip): tooltip w/ design system
  src/Theme/colors.js
  src/Theme/tooltip.js
  src/components/Overlays/Tooltip/ThemedTooltip.js
  src/components/Overlays/Tooltip/ThemedTooltip/ThemedArrow.js
  src/components/Overlays/Tooltip/ThemedTooltip/ThemedContent.js
  src/components/Overlays/Tooltip/ThemedTooltip/ThemedWrapper.js
  src/components/Overlays/Tooltip/Tooltip.js
  src/components/Overlays/Tooltip/Tooltip.mdx
  src/components/Overlays/Tooltip/Tooltip.scss
  src/components/Overlays/WithTooltip/WithTooltip.js
  src/helpers/DocBlocks/CodeBlock/CodeBlock.js
  src/hooks/usePositioner/constants.js
  src/hooks/usePositioner/usePositioner.js
Labels: enhancement, feature

#460 fix(range picker): default end date value if not selected
  src/components/Inputs/Date/__tests__/Date.basic.test.js
  src/components/Inputs/Date/components/RangeComparison/RangePicker.js
Labels: bug

#463 enhancement(loader): add styled component capability
  src/components/UI/Loader/Loader.js
  src/components/UI/Loader/Loader.mdx
  src/components/UI/Loader/Loader.scss
  src/components/UI/Loader/ThemedLoader.js
Labels: enhancement

#462 fix(button): change font-size definition
  src/Theme/button.js
  src/components/UI/Button/Button.js
  src/components/UI/Button/ThemedButton.js
Labels: bug
