Repository hellohaptik/relements, pull requests merged in 2021-04, with the labels that each got.

#466 fix(withtooltip): change default value of tooltip to null
  src/components/Overlays/WithTooltip/WithTooltip.js
Labels: bug

#467 Revert "fix(withtooltip): change default value of tooltip to null (#466)"
  src/components/Overlays/WithTooltip/WithTooltip.js
Labels: bug

#474 fix(storybook): add color token, test release
  src/Theme/tokens.storybook.js
Labels: bug

#461 feat(dropdown): integrate design system w/dropdown
  src/Theme/Theme.js
  src/Theme/chipsInput.js
  src/Theme/dropdown.js
  src/Theme/label.js
  src/Theme/textInput.js
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/Dropdown.mdx
  src/components/Inputs/Dropdown/ThemedDropdown.js
  src/components/Inputs/Dropdown/components/Input/Input.js
  src/components/Inputs/Dropdown/components/Option/Option.js
  src/components/Inputs/Dropdown/components/Options/Options.js
  src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.js
  src/components/Inputs/Dropdown/constants.js
  src/components/Inputs/Dropdown/utils/getOptions.js
  src/components/Inputs/Text/Text.js
  src/components/Inputs/Text/Text.mdx
  src/components/Inputs/_common/ChipsInput.js
  src/components/Inputs/_common/ChipsInput.scss
  src/components/Inputs/_common/Label.js
  src/components/Inputs/_common/TextInput.js
  src/components/Inputs/_common/ThemedChipsInput.js
  src/components/Inputs/_common/ThemedLabel.js
  src/components/Inputs/_common/ThemedTextInput.js
  src/components/Overlays/Tooltip/ThemedTooltip.js
  src/icons/closeV3.svg
Labels: enhancement, feature

#475 fix(build): remove disabled flag
  .releaserc.js
Labels: bug

#477 fix(config): import order
  .storybook/config.js
Labels: bug

#476 improvement(dropdown): add themed checkbox and improvements
  src/Theme/dropdown.js
  src/components/Inputs/Dropdown/Dropdown.js
  src/components/Inputs/Dropdown/Dropdown.mdx
  src/components/Inputs/Dropdown/ThemedDropdown.js
  src/components/Inputs/Dropdown/components/Options/Options.js
  src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.js
Labels: enhancement

#478 fix(dropdown): fix spacing in import
  src/components/Inputs/Dropdown/ThemedDropdown.js
Labels: bug

#481 fix(checkbox): fix themed checkbox missing label
  src/Theme/checkbox.js
  src/components/Inputs/Checkbox/Checkbox.js
  src/components/Inputs/Checkbox/Checkbox.mdx
  src/components/Inputs/Checkbox/CheckboxItem.mdx
  src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxWrapper.js
Labels: bug
